//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSAPToDB
    {
        public long LogId { get; set; }
        public string Json { get; set; }
        public string ApplicationId { get; set; }
        public string Status { get; set; }
        public string ControllerAction { get; set; }
        public string JsonMessageError { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Count { get; set; }
    }
}
