//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUNACC_RASIO_TEMP
    {
        public long ID { get; set; }
        public string SEL { get; set; }
        public string EQUNR { get; set; }
        public string EQKTX { get; set; }
        public string KOSTL { get; set; }
        public string RUNNINGACCOUNT { get; set; }
        public string ESTATE { get; set; }
        public string COMPANYCODE { get; set; }
        public string CONSSOLAR { get; set; }
        public string CONSSOLARHSD { get; set; }
        public string TOTALKM { get; set; }
        public string TOTALHOUR { get; set; }
        public string TOTALFUELCONS { get; set; }
        public string RASIOKML { get; set; }
        public string TOTALFUELHOUR { get; set; }
        public string TRIP { get; set; }
        public string NETWEIGHT { get; set; }
        public string EFISIENSI { get; set; }
        public string KGTRIP { get; set; }
        public string COSTACTUAL { get; set; }
        public string RPTOTALKM { get; set; }
        public string RPTOTALHOUR { get; set; }
        public string RPKG { get; set; }
        public string TOTALHARIKERJA { get; set; }
        public string COSTLABOUR { get; set; }
        public string COSTTRANSPORT { get; set; }
        public string OTHEREXPENSE { get; set; }
        public string COSTMATERIAL { get; set; }
        public string PERIOD { get; set; }
        public string ZYEAR { get; set; }
    }
}
