//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES_MOBILE_STOCK_TEMP
    {
        public int ID { get; set; }
        public string MANDT { get; set; }
        public string BUKRS { get; set; }
        public string AREA { get; set; }
        public string WERKS { get; set; }
        public string MATNR { get; set; }
        public string ASOFDATE { get; set; }
        public string BUTXT { get; set; }
        public string NAME1 { get; set; }
        public string ZBEGSTOCK { get; set; }
        public string ZRECSTOCK { get; set; }
        public string ZDEL { get; set; }
        public string ZINSTOCK { get; set; }
        public string ZOTHSTOCK { get; set; }
        public string ZENDSTOCK { get; set; }
        public string CF05 { get; set; }
        public string OUTSKONTRAK { get; set; }
        public string CREATEDDATE { get; set; }
    }
}
