//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZC0032
    {
        public string MANDT { get; set; }
        public string GJAHR { get; set; }
        public string MONAT { get; set; }
        public string WERKS { get; set; }
        public string TYPE { get; set; }
        public string ITEM { get; set; }
        public string ITEMTEXT { get; set; }
        public decimal AOP1YR { get; set; }
        public decimal YTDAOP { get; set; }
        public decimal YTDCOST { get; set; }
        public decimal YTDSISA { get; set; }
        public decimal Z01AOP { get; set; }
        public decimal Z01COST { get; set; }
        public decimal Z01SISA { get; set; }
        public decimal Z02AOP { get; set; }
        public decimal Z02COST { get; set; }
        public decimal Z02SISA { get; set; }
        public decimal Z03AOP { get; set; }
        public decimal Z03COST { get; set; }
        public decimal Z03SISA { get; set; }
        public decimal Z04AOP { get; set; }
        public decimal Z04COST { get; set; }
        public decimal Z04SISA { get; set; }
        public decimal Z05AOP { get; set; }
        public decimal Z05COST { get; set; }
        public decimal Z05SISA { get; set; }
        public decimal Z06AOP { get; set; }
        public decimal Z06COST { get; set; }
        public decimal Z06SISA { get; set; }
        public decimal Z07AOP { get; set; }
        public decimal Z07COST { get; set; }
        public decimal Z07SISA { get; set; }
        public decimal Z08AOP { get; set; }
        public decimal Z08COST { get; set; }
        public decimal Z08SISA { get; set; }
        public decimal Z09AOP { get; set; }
        public decimal Z09COST { get; set; }
        public decimal Z09SISA { get; set; }
        public decimal Z10AOP { get; set; }
        public decimal Z10COST { get; set; }
        public decimal Z10SISA { get; set; }
        public decimal Z11AOP { get; set; }
        public decimal Z11COST { get; set; }
        public decimal Z11SISA { get; set; }
        public decimal Z12AOP { get; set; }
        public decimal Z12COST { get; set; }
        public decimal Z12SISA { get; set; }
        public string CLASS { get; set; }
        public string JOBDAT { get; set; }
        public string JOBNAM { get; set; }
        public string WAERS { get; set; }
        public System.DateTime INSERTDATE { get; set; }
    }
}
