//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTF_CDV_LASTMAIL
    {
        public string CDVId { get; set; }
        public string Cdcomp { get; set; }
        public string Cdgsber { get; set; }
        public string Approver { get; set; }
        public string Nrcdv { get; set; }
        public string Nrbelnr { get; set; }
        public Nullable<decimal> Amtotal { get; set; }
        public string Cutotal { get; set; }
        public string Txberita { get; set; }
        public string Txberita1 { get; set; }
        public string Txberita2 { get; set; }
        public string Docnum { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string NMPAYEE { get; set; }
        public string NMGSBER { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isSuccessPostToSAP { get; set; }
        public string ErrorMessage { get; set; }
        public string Client { get; set; }
    }
}
