//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTM_MATPRC_MIP_TEMP
    {
        public long ID { get; set; }
        public string MANDT { get; set; }
        public string MATGRP { get; set; }
        public string AREA1 { get; set; }
        public string MATNR { get; set; }
        public string MATGRPDESC { get; set; }
        public string LSTPRD { get; set; }
        public string TXZ01 { get; set; }
        public string LSTPO { get; set; }
        public string LSTPOITEM { get; set; }
        public string WAERS { get; set; }
        public string TOTVAL { get; set; }
        public string LSTPRC { get; set; }
        public string LSTUOM { get; set; }
    }
}
