//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTM_YTDTPURC_MIP_TEMP
    {
        public long ID { get; set; }
        public string MANDT { get; set; }
        public string COMPGRP { get; set; }
        public string MATGRP { get; set; }
        public string MATGRPDESC { get; set; }
        public string LSTPRD { get; set; }
        public string LSTPRDTOT { get; set; }
        public string YTDTOT { get; set; }
        public string WAERS { get; set; }
    }
}
