//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTM_ORDER_PO
    {
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public string MBLNR { get; set; }
        public string MATNR { get; set; }
        public string OBJEK { get; set; }
        public string ERNAM { get; set; }
        public string BUKRS { get; set; }
        public string BUTXT { get; set; }
        public string EKGRP { get; set; }
        public string EKNAM { get; set; }
        public string AREA { get; set; }
        public string WERKS { get; set; }
        public string PLTNM { get; set; }
        public string BSART { get; set; }
        public string TRANS_CODE { get; set; }
        public string TRANS_NAME { get; set; }
        public string PR_TEXT { get; set; }
        public string PO_HTEXT { get; set; }
        public string PO_ITEXT { get; set; }
        public string LIFNR { get; set; }
        public string ANRED { get; set; }
        public string NAME1 { get; set; }
        public string LIFRE { get; set; }
        public string LIFNM { get; set; }
        public string STRAS { get; set; }
        public string ORT01 { get; set; }
        public string PSTLZ { get; set; }
        public string TELF1 { get; set; }
        public string TELFX { get; set; }
        public string EMAIL { get; set; }
        public string VERKF { get; set; }
        public Nullable<System.DateTime> BEDAT { get; set; }
        public Nullable<System.DateTime> PORELDT { get; set; }
        public string KPOSN { get; set; }
        public string KNTTP { get; set; }
        public string PSTYP { get; set; }
        public string TXZ01 { get; set; }
        public string CAPITAL { get; set; }
        public string CAPDESC { get; set; }
        public string MATGRP { get; set; }
        public string WGBEZ2 { get; set; }
        public string SUBGRP { get; set; }
        public string SDESC { get; set; }
        public string MATKL { get; set; }
        public string WGBEZ { get; set; }
        public string EXTWG { get; set; }
        public string GRULNM { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> PEINH { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> P001 { get; set; }
        public Nullable<decimal> RA00 { get; set; }
        public Nullable<decimal> PCTRA { get; set; }
        public Nullable<decimal> FRA1 { get; set; }
        public Nullable<decimal> ZOTH { get; set; }
        public Nullable<decimal> ZINS { get; set; }
        public Nullable<decimal> ZCLR { get; set; }
        public Nullable<decimal> ZPPN { get; set; }
        public Nullable<decimal> ZDEL { get; set; }
        public Nullable<decimal> ZTA1 { get; set; }
        public Nullable<decimal> ZCS1 { get; set; }
        public Nullable<decimal> ZCSTOT { get; set; }
        public string XZPPN { get; set; }
        public string XZDEL { get; set; }
        public string XZTA1 { get; set; }
        public string XZCS1 { get; set; }
        public Nullable<decimal> PRCORG { get; set; }
        public Nullable<decimal> VALORG { get; set; }
        public Nullable<decimal> WKURS { get; set; }
        public Nullable<decimal> PRCIDR { get; set; }
        public Nullable<decimal> VALIDR { get; set; }
        public string WAERS2 { get; set; }
        public string INCO1 { get; set; }
        public string INCO2 { get; set; }
        public string LGORT { get; set; }
        public string ZTERM { get; set; }
        public string TEXT1 { get; set; }
        public string FRGGR { get; set; }
        public string FRGSX { get; set; }
        public string FRGKE { get; set; }
        public string FRGZU { get; set; }
        public Nullable<System.DateTime> EINDT { get; set; }
        public Nullable<decimal> WEMNG { get; set; }
        public string LOEKZ { get; set; }
        public string UEBTK { get; set; }
        public Nullable<System.DateTime> BUDAT { get; set; }
        public Nullable<decimal> GRQTY { get; set; }
        public string GRUOM { get; set; }
        public string GRLOC { get; set; }
        public Nullable<decimal> GRPRC { get; set; }
        public Nullable<decimal> GRVAL { get; set; }
        public Nullable<decimal> OUTPO { get; set; }
        public Nullable<decimal> OUTPOV { get; set; }
        public string ELIKZ { get; set; }
        public Nullable<decimal> ACHPCT { get; set; }
        public string XBLNR { get; set; }
        public string BANFN { get; set; }
        public string BNFPO { get; set; }
        public Nullable<System.DateTime> BADAT { get; set; }
        public Nullable<System.DateTime> RELDT2 { get; set; }
        public Nullable<System.DateTime> FRGDT { get; set; }
        public string FRGKZ { get; set; }
        public Nullable<System.DateTime> LFDAT { get; set; }
        public Nullable<decimal> MENGE2 { get; set; }
        public string MEINS2 { get; set; }
        public Nullable<decimal> BSMNG { get; set; }
        public string DISPO { get; set; }
        public string AFNAM { get; set; }
        public string BEDNR { get; set; }
        public string ERNAM2 { get; set; }
        public string SUBMI { get; set; }
        public string ANFNR { get; set; }
        public string SAKTO { get; set; }
        public string TXT50 { get; set; }
        public string KOSTL { get; set; }
        public string LTEXT { get; set; }
        public string ANLN1 { get; set; }
        public string TXT502 { get; set; }
        public string OBJNR { get; set; }
        public string PS_PSP_PNR { get; set; }
        public string POST1 { get; set; }
        public string POSID { get; set; }
        public string PRART { get; set; }
        public string PRATX { get; set; }
        public string COTYP { get; set; }
        public string AUFNR { get; set; }
        public string AUART { get; set; }
        public string TXT { get; set; }
        public string BELNR { get; set; }
        public Nullable<decimal> INVAMT { get; set; }
        public Nullable<System.DateTime> BUDAT2 { get; set; }
        public Nullable<System.DateTime> DUEDAT { get; set; }
        public Nullable<System.DateTime> ZFBDT { get; set; }
        public Nullable<int> ZBD1T { get; set; }
        public string MWSKZ { get; set; }
        public string EBAKZ { get; set; }
        public string KNUMV { get; set; }
        public string OBJECTID { get; set; }
        public string KEYPO { get; set; }
        public string WEBRE { get; set; }
        public Nullable<int> LD01 { get; set; }
        public Nullable<int> LD02 { get; set; }
        public Nullable<int> LD03 { get; set; }
        public Nullable<int> LD04 { get; set; }
        public string KALSK { get; set; }
        public string EKORG { get; set; }
        public string POCTR { get; set; }
        public Nullable<System.DateTime> HTCHG { get; set; }
        public Nullable<System.DateTime> ITCHG { get; set; }
        public string EAN11 { get; set; }
        public string ATWTB1 { get; set; }
        public string ATWTB2 { get; set; }
        public string ATWTB3 { get; set; }
        public string ATWTB4 { get; set; }
        public string ATWTB5 { get; set; }
        public Nullable<System.DateTime> JOBDAT { get; set; }
        public string JOBNAM { get; set; }
        public Nullable<System.DateTime> AEDAT { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public string CLIENT { get; set; }
    }
}
