//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTM_PR_LIST
    {
        public string BUKRS { get; set; }
        public string WERKS { get; set; }
        public string BANFN { get; set; }
        public string BNFPO { get; set; }
        public string EBELN { get; set; }
        public string EBELP { get; set; }
        public string EKGRP { get; set; }
        public string EKGRP_PO { get; set; }
        public string MATNR { get; set; }
        public string NOMOR { get; set; }
        public string NAME1 { get; set; }
        public string ELIKZ { get; set; }
        public string AREA { get; set; }
        public string AREA1 { get; set; }
        public string CMGRP { get; set; }
        public string SHORT { get; set; }
        public string KNTTP { get; set; }
        public string TXZ01 { get; set; }
        public string CAPITAL { get; set; }
        public string CAPDESC { get; set; }
        public string MATGRP { get; set; }
        public string WGBEZ2 { get; set; }
        public string SUBGRP { get; set; }
        public string SDESC { get; set; }
        public string MATKL { get; set; }
        public string WGBEZ { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public Nullable<decimal> BSMNG { get; set; }
        public Nullable<decimal> OQTY { get; set; }
        public string EBAKZ { get; set; }
        public string MEINS { get; set; }
        public Nullable<System.DateTime> LFDAT { get; set; }
        public Nullable<System.DateTime> FRGDT { get; set; }
        public Nullable<System.DateTime> BADAT { get; set; }
        public Nullable<System.DateTime> RELDT { get; set; }
        public string AFNAM { get; set; }
        public string IDNLF { get; set; }
        public string HDRTXT { get; set; }
        public string STRTXT { get; set; }
        public string EKNAM { get; set; }
        public string LOEKZ { get; set; }
        public string STATU { get; set; }
        public string FRGKZ { get; set; }
        public Nullable<System.DateTime> ERDAT { get; set; }
        public string FRGZU { get; set; }
        public string ANLN1 { get; set; }
        public string TXT502 { get; set; }
        public string KOSTL { get; set; }
        public string LTEXT { get; set; }
        public string SAKTO { get; set; }
        public string TXT50 { get; set; }
        public string AUFNR { get; set; }
        public string POSID { get; set; }
        public string POST1 { get; set; }
        public string ERNAM { get; set; }
        public Nullable<System.DateTime> BEDAT { get; set; }
        public Nullable<decimal> POQTY { get; set; }
        public string FRGGR { get; set; }
        public string FRGST { get; set; }
        public Nullable<decimal> PREIS { get; set; }
        public Nullable<decimal> PEINH { get; set; }
        public Nullable<decimal> AMTPR { get; set; }
        public string WAERS { get; set; }
        public string STATUS { get; set; }
        public string STRSTATUS { get; set; }
        public Nullable<int> SBTTL { get; set; }
        public Nullable<System.DateTime> GRPCHG { get; set; }
        public string ESTKZ { get; set; }
        public Nullable<System.DateTime> PORELDT { get; set; }
        public Nullable<System.DateTime> RFQDT { get; set; }
        public Nullable<int> OUTDAYS { get; set; }
        public string COTYP { get; set; }
        public string BLCKD { get; set; }
        public string BLCKT { get; set; }
        public string OVERPOSTO { get; set; }
        public string SWERK { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> JOBDAT { get; set; }
        public string JOBNAM { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public string CLIENT { get; set; }
    }
}
