//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTMAGRI_STOCKPRD
    {
        public string BDATJ { get; set; }
        public string POPER { get; set; }
        public string BUKRS { get; set; }
        public string WERKS { get; set; }
        public string MATNR { get; set; }
        public string BWTAR { get; set; }
        public string MTART { get; set; }
        public string BKLAS { get; set; }
        public string MATKL { get; set; }
        public string KTEXT { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> PVPRS { get; set; }
        public string PEINH { get; set; }
        public Nullable<decimal> LBKUM { get; set; }
        public Nullable<decimal> SALK3 { get; set; }
        public string SPART { get; set; }
        public string PSPNR { get; set; }
        public string MLAST { get; set; }
        public string VPRSV { get; set; }
        public string WAERS { get; set; }
        public string STATUS { get; set; }
        public string STATUSTEXT { get; set; }
        public string CREATEDDATE { get; set; }
        public string CREATEDNAME { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public string CLIENT { get; set; }
    }
}
