//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTPAGRI_MILLPROD
    {
        public string MANDT { get; set; }
        public string WERKS { get; set; }
        public string GJAHR { get; set; }
        public string MONAT { get; set; }
        public string AUFNR { get; set; }
        public string STATUS { get; set; }
        public string ERSDA { get; set; }
        public string CPUTM { get; set; }
        public string ERNAM { get; set; }
        public string LAEDA { get; set; }
        public string UPDDT { get; set; }
        public string AENAM { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
