//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTPAGRI_MILLDATA
    {
        public string MANDT { get; set; }
        public string BUKRS { get; set; }
        public string WERKS { get; set; }
        public string GJAHR { get; set; }
        public string MONAT { get; set; }
        public string PRD_DATE { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
        public Nullable<decimal> FFBOPN { get; set; }
        public Nullable<decimal> FFBRTY { get; set; }
        public Nullable<decimal> FFBRTD { get; set; }
        public Nullable<decimal> FFBPTY { get; set; }
        public Nullable<decimal> FFBPTD { get; set; }
        public Nullable<decimal> FFBCLS { get; set; }
        public Nullable<decimal> CPOOPN1 { get; set; }
        public Nullable<decimal> CPOOPN2 { get; set; }
        public Nullable<decimal> CPOOPN3 { get; set; }
        public Nullable<decimal> CPOOPN4 { get; set; }
        public Nullable<decimal> CPOOPEN { get; set; }
        public Nullable<decimal> CPOPRD1 { get; set; }
        public Nullable<decimal> CPOPRD2 { get; set; }
        public Nullable<decimal> CPOPRD3 { get; set; }
        public Nullable<decimal> CPOPRD4 { get; set; }
        public Nullable<decimal> CPOPTY { get; set; }
        public Nullable<decimal> CPOPTD { get; set; }
        public Nullable<decimal> OER { get; set; }
        public Nullable<decimal> OERTD { get; set; }
        public Nullable<decimal> FFAPTY { get; set; }
        public Nullable<decimal> FFAPTD { get; set; }
        public Nullable<decimal> CPODIS1 { get; set; }
        public Nullable<decimal> CPODIS2 { get; set; }
        public Nullable<decimal> CPODIS3 { get; set; }
        public Nullable<decimal> CPODIS4 { get; set; }
        public Nullable<decimal> CPODTY { get; set; }
        public Nullable<decimal> CPODTD { get; set; }
        public Nullable<decimal> CPOOTR1 { get; set; }
        public Nullable<decimal> CPOOTR2 { get; set; }
        public Nullable<decimal> CPOOTR3 { get; set; }
        public Nullable<decimal> CPOOTR4 { get; set; }
        public Nullable<decimal> CPOOGL1 { get; set; }
        public Nullable<decimal> CPOOGL2 { get; set; }
        public Nullable<decimal> CPOOGL3 { get; set; }
        public Nullable<decimal> CPOOGL4 { get; set; }
        public Nullable<decimal> CPOCLS1 { get; set; }
        public Nullable<decimal> FFACPO1 { get; set; }
        public Nullable<decimal> CPOCLS2 { get; set; }
        public Nullable<decimal> FFACPO2 { get; set; }
        public Nullable<decimal> CPOCLS3 { get; set; }
        public Nullable<decimal> FFACPO3 { get; set; }
        public Nullable<decimal> CPOCLS4 { get; set; }
        public Nullable<decimal> FFACPO4 { get; set; }
        public Nullable<decimal> CPOCLOSE { get; set; }
        public Nullable<decimal> PKOPNBS { get; set; }
        public Nullable<decimal> PKOPNOT { get; set; }
        public Nullable<decimal> PKOPEN { get; set; }
        public Nullable<decimal> PKPROD { get; set; }
        public Nullable<decimal> PKPRDFN { get; set; }
        public Nullable<decimal> PKPRDTY { get; set; }
        public Nullable<decimal> PKPRDTD { get; set; }
        public Nullable<decimal> PKEXTRT { get; set; }
        public Nullable<decimal> PKEXTD { get; set; }
        public Nullable<decimal> PKDISTY { get; set; }
        public Nullable<decimal> PKDISTD { get; set; }
        public Nullable<decimal> PKOTHTFN { get; set; }
        public Nullable<decimal> PKOTHRFN { get; set; }
        public Nullable<decimal> PKOTHGL { get; set; }
        public Nullable<decimal> PKOTHTD { get; set; }
        public Nullable<decimal> PKCLSBS { get; set; }
        public Nullable<decimal> PKCLSOT { get; set; }
        public Nullable<decimal> PKCLOSE { get; set; }
        public string MILLSTR { get; set; }
        public string MILLSTP { get; set; }
        public Nullable<decimal> PERHRTY { get; set; }
        public Nullable<decimal> PERHRTD { get; set; }
        public Nullable<decimal> BREAKDO { get; set; }
        public Nullable<decimal> UTYHRTY { get; set; }
        public Nullable<decimal> UTYHRTD { get; set; }
        public Nullable<decimal> MILUTTY { get; set; }
        public Nullable<decimal> MILUTTD { get; set; }
        public Nullable<decimal> MILTHTY { get; set; }
        public Nullable<decimal> MILTHTD { get; set; }
        public string REMARK { get; set; }
        public string ERSDA { get; set; }
        public string CPUTM { get; set; }
        public string ERNAM { get; set; }
        public string LAEDA { get; set; }
        public string UPDDT { get; set; }
        public string AENAM { get; set; }
        public Nullable<decimal> CPOPRD5 { get; set; }
        public Nullable<decimal> CPOPRD6 { get; set; }
        public Nullable<decimal> CPODIS5 { get; set; }
        public Nullable<decimal> CPODIS6 { get; set; }
        public Nullable<decimal> CPOOGL5 { get; set; }
        public Nullable<decimal> CPOOGL6 { get; set; }
        public Nullable<decimal> CPOCLS5 { get; set; }
        public Nullable<decimal> CPOCLS6 { get; set; }
        public Nullable<decimal> FFACPO5 { get; set; }
        public Nullable<decimal> FFACPO6 { get; set; }
        public Nullable<decimal> CPOOTR5 { get; set; }
        public Nullable<decimal> CPOOTR6 { get; set; }
        public Nullable<decimal> CPOOPN5 { get; set; }
        public Nullable<decimal> CPOOPN6 { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
