//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTUAGRI_PBS2_RPT_TEMP
    {
        public Nullable<int> ZYEAR { get; set; }
        public string SPBSNUM { get; set; }
        public string COMPANYCODE { get; set; }
        public string ESTATE { get; set; }
        public string DIVISI { get; set; }
        public string SPBSDATE { get; set; }
        public string PLASMAID { get; set; }
        public string ASSTID { get; set; }
        public string KRANI { get; set; }
        public string MILL { get; set; }
        public string MILLEX { get; set; }
        public string SOPIR { get; set; }
        public string JARAK { get; set; }
        public string NOPOL { get; set; }
        public string WBNUM { get; set; }
        public string NET { get; set; }
        public string CREATEDDATE { get; set; }
        public string LASTUPDATEDDATE { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string UOM { get; set; }
        public string UOMJRK { get; set; }
        public string REVIEW { get; set; }
        public string SAPNUM { get; set; }
        public string REFDOC { get; set; }
        public string STATUS { get; set; }
        public string INEX { get; set; }
        public string RECALNUM { get; set; }
        public string LOADDATE { get; set; }
        public string MULTI { get; set; }
        public string ACTPLASMA { get; set; }
        public string UPLOAD { get; set; }
        public string LBKNUM { get; set; }
        public string RUNNING_ACCOUNT { get; set; }
        public int LINENUM { get; set; }
        public string BLOCKID { get; set; }
        public string ZDATE { get; set; }
        public string JANJANG { get; set; }
        public string JJGUOM { get; set; }
        public string TAKJANJANG { get; set; }
        public string TAKBROND { get; set; }
        public string TAKTOTAL { get; set; }
        public string ACTUAL { get; set; }
        public string LBKNUM_ITEM { get; set; }
        public string SHIPTYPE { get; set; }
        public string SHIPDATE { get; set; }
        public string SHIPTRIP { get; set; }
        public int WEEK { get; set; }
        public Nullable<int> PERIODE { get; set; }
        public string kernet { get; set; }
        public string WBNUMEST { get; set; }
        public string NETEST { get; set; }
    }
}
