//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTUAGRI_BP
    {
        public int ZYEAR { get; set; }
        public string PANENNUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string ESTATE { get; set; }
        public string DIVISI { get; set; }
        public string BKMNUM { get; set; }
        public string EMPID { get; set; }
        public int LINENUM { get; set; }
        public System.DateTime BPDATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string REVIEW { get; set; }
        public string SAPNUM { get; set; }
        public string REFDOC { get; set; }
        public string LOCID { get; set; }
        public string UPLOAD { get; set; }
        public int LINENUM_I { get; set; }
        public string PRODTYPE { get; set; }
        public string BLOCKID { get; set; }
        public Nullable<decimal> ACTL { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> DRC { get; set; }
        public string TPH { get; set; }
        public string UOMDRC { get; set; }
        public string LB { get; set; }
        public string REVIEW_I { get; set; }
        public Nullable<decimal> MNDR_HK { get; set; }
        public Nullable<decimal> KARY_HK { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> WEEK { get; set; }
        public Nullable<int> PERIOD { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
