//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.IndoAgriData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTW_ASSETSTAT
    {
        public string AssetStatId { get; set; }
        public string Werks { get; set; }
        public Nullable<System.DateTime> Erdat { get; set; }
        public string Eqart { get; set; }
        public string Good { get; set; }
        public Nullable<int> Broken { get; set; }
        public Nullable<int> Total { get; set; }
        public string Ernam { get; set; }
        public Nullable<System.DateTime> Endat { get; set; }
        public string Rzet { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateTime { get; set; }
    }
}
