//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.Approval.Api.ServiceAuthSAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3")]
    public interface ZSDUAGRI_GSBER_DEFAULT3 {
        
        // CODEGEN: Generating message contract since the operation ZuagriGsberDefaultEmpty is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZSDUAGRI_GSBER_DEFAULT3:ZuagriGs" +
            "berDefaultEmptyRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse1 ZuagriGsberDefaultEmpty(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZSDUAGRI_GSBER_DEFAULT3:ZuagriGs" +
            "berDefaultEmptyRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse1> ZuagriGsberDefaultEmptyAsync(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZuagriGsberDefaultEmpty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZustAgriAuthorization[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZustAgriAuthorization[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZustAgriAuthorization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bukrsField;
        
        private string gsberField;
        
        private string divisiField;
        
        private string tcodeField;
        
        private string activityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
                this.RaisePropertyChanged("Bukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Gsber {
            get {
                return this.gsberField;
            }
            set {
                this.gsberField = value;
                this.RaisePropertyChanged("Gsber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Divisi {
            get {
                return this.divisiField;
            }
            set {
                this.divisiField = value;
                this.RaisePropertyChanged("Divisi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Tcode {
            get {
                return this.tcodeField;
            }
            set {
                this.tcodeField = value;
                this.RaisePropertyChanged("Tcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
                this.RaisePropertyChanged("Activity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZuagriGsberDefaultEmptyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZustAgriAuthorization[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZustAgriAuthorization[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZuagriGsberDefaultEmptyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmpty ZuagriGsberDefaultEmpty;
        
        public ZuagriGsberDefaultEmptyRequest() {
        }
        
        public ZuagriGsberDefaultEmptyRequest(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmpty ZuagriGsberDefaultEmpty) {
            this.ZuagriGsberDefaultEmpty = ZuagriGsberDefaultEmpty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZuagriGsberDefaultEmptyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse ZuagriGsberDefaultEmptyResponse;
        
        public ZuagriGsberDefaultEmptyResponse1() {
        }
        
        public ZuagriGsberDefaultEmptyResponse1(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse ZuagriGsberDefaultEmptyResponse) {
            this.ZuagriGsberDefaultEmptyResponse = ZuagriGsberDefaultEmptyResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZSDUAGRI_GSBER_DEFAULT3Channel : IndoAgri.Approval.Api.ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZSDUAGRI_GSBER_DEFAULT3Client : System.ServiceModel.ClientBase<IndoAgri.Approval.Api.ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3>, IndoAgri.Approval.Api.ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3 {
        
        public ZSDUAGRI_GSBER_DEFAULT3Client() {
        }
        
        public ZSDUAGRI_GSBER_DEFAULT3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZSDUAGRI_GSBER_DEFAULT3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSDUAGRI_GSBER_DEFAULT3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSDUAGRI_GSBER_DEFAULT3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse1 IndoAgri.Approval.Api.ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3.ZuagriGsberDefaultEmpty(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest request) {
            return base.Channel.ZuagriGsberDefaultEmpty(request);
        }
        
        public IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse ZuagriGsberDefaultEmpty(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmpty ZuagriGsberDefaultEmpty1) {
            IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest inValue = new IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest();
            inValue.ZuagriGsberDefaultEmpty = ZuagriGsberDefaultEmpty1;
            IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse1 retVal = ((IndoAgri.Approval.Api.ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3)(this)).ZuagriGsberDefaultEmpty(inValue);
            return retVal.ZuagriGsberDefaultEmptyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse1> IndoAgri.Approval.Api.ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3.ZuagriGsberDefaultEmptyAsync(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest request) {
            return base.Channel.ZuagriGsberDefaultEmptyAsync(request);
        }
        
        public System.Threading.Tasks.Task<IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyResponse1> ZuagriGsberDefaultEmptyAsync(IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmpty ZuagriGsberDefaultEmpty) {
            IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest inValue = new IndoAgri.Approval.Api.ServiceAuthSAP.ZuagriGsberDefaultEmptyRequest();
            inValue.ZuagriGsberDefaultEmpty = ZuagriGsberDefaultEmpty;
            return ((IndoAgri.Approval.Api.ServiceAuthSAP.ZSDUAGRI_GSBER_DEFAULT3)(this)).ZuagriGsberDefaultEmptyAsync(inValue);
        }
    }
}
