//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriPOICAT.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPlant
    {
        public string WERKS { get; set; }
        public string NAME1 { get; set; }
        public string KUNNR { get; set; }
        public string LIFNR { get; set; }
        public Nullable<decimal> POMax { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
