//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriPOICAT.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDeliveryAddress
    {
        public string WERKS { get; set; }
        public string ADDRNUMBER { get; set; }
        public string LGORT { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string STREET { get; set; }
        public string POST_CODE1 { get; set; }
        public string TEL_NUMBER { get; set; }
        public string CITY1 { get; set; }
        public string REGION { get; set; }
        public string AREA1 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
