//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriPOICAT.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPlantArea
    {
        public string WERKS { get; set; }
        public string BUKRS { get; set; }
        public string AREA { get; set; }
        public string AREA1 { get; set; }
        public string SHORT { get; set; }
        public Nullable<int> ZSEQ { get; set; }
        public string ZSEQ2 { get; set; }
        public string CMGRP { get; set; }
        public string PLTTYP { get; set; }
        public string EMOPR { get; set; }
        public string EMTRK { get; set; }
        public string USKTU1 { get; set; }
        public string USKTU2 { get; set; }
        public string EKGRP1 { get; set; }
        public string EKGRP2 { get; set; }
        public string EKNAM1 { get; set; }
        public string EKNAM2 { get; set; }
        public string FRGCO1 { get; set; }
        public string FRGCO2 { get; set; }
        public string EMKTU { get; set; }
        public string USMGR { get; set; }
        public string RELMGR { get; set; }
        public string RELMGR2 { get; set; }
        public string EMMGR { get; set; }
        public string USAMA { get; set; }
        public string RELAMA { get; set; }
        public string RELAMA2 { get; set; }
        public string EMAMA { get; set; }
        public string EMAMAS { get; set; }
        public string USVPA { get; set; }
        public string RELVPA { get; set; }
        public string RELVPA2 { get; set; }
        public string EMVPA { get; set; }
        public string EMVPAS { get; set; }
        public string RELCOO { get; set; }
        public string RELCOO2 { get; set; }
        public string EMCOO { get; set; }
        public string EMCOOS { get; set; }
        public string RELCFO { get; set; }
        public string RELCFO2 { get; set; }
        public string EMCFO { get; set; }
        public string EMCFOS { get; set; }
        public string SUPPORT_TEAM { get; set; }
        public string RELCEO { get; set; }
        public string RELCEO2 { get; set; }
        public string EMCEO { get; set; }
        public string EMCEOS { get; set; }
        public string EMSITE { get; set; }
        public string EMRO { get; set; }
        public string EMHO { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
