//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriPOICAT.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParTable
    {
        public ParTable()
        {
            this.ParEntries = new HashSet<ParEntry>();
        }
    
        public int Id { get; set; }
        public string Sdesc { get; set; }
        public string Ldesc { get; set; }
        public Nullable<int> Ref1 { get; set; }
        public Nullable<int> Ref2 { get; set; }
        public Nullable<int> Ref3 { get; set; }
        public Nullable<int> Ref4 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<ParEntry> ParEntries { get; set; }
    }
}
