//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriPOICAT.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunningNumber
    {
        public int rn_ID { get; set; }
        public string rn_FormCode { get; set; }
        public Nullable<int> rn_number { get; set; }
        public Nullable<int> rn_Year { get; set; }
        public Nullable<int> rn_Month { get; set; }
        public Nullable<int> rn_Date { get; set; }
    }
}
