//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriPOICAT.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateNotifEmail
    {
        public int tpl_ID { get; set; }
        public string tpl_Template { get; set; }
        public string tpl_Subject { get; set; }
        public string tpl_ProcessNameCode { get; set; }
        public string tpl_ModuleCode { get; set; }
        public Nullable<long> tpl_IsEnabled { get; set; }
        public System.DateTime tpl_CreatedOn { get; set; }
        public string tpl_CreatedBy { get; set; }
        public Nullable<System.DateTime> tpl_UpdatedOn { get; set; }
        public string tpl_UpdatedBy { get; set; }
        public Nullable<System.DateTime> tpl_DeletedOn { get; set; }
    }
}
