//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriPOICAT.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorData
    {
        public int UserId { get; set; }
        public string SAPVendorCode { get; set; }
        public long IDBasicData { get; set; }
        public int VendorCode { get; set; }
        public string VendorName { get; set; }
        public string Email { get; set; }
        public string EmailCC { get; set; }
        public string EmailCC2 { get; set; }
        public string TermOfPayment { get; set; }
        public bool IsPKP { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
