//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriIACData.Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IAC_AGRIDATAEntities : DbContext
    {
        public IAC_AGRIDATAEntities()
            : base("name=IAC_AGRIDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ZTUAGRI_HK> ZTUAGRI_HK { get; set; }
        public virtual DbSet<ZTUAGRI_HK_TESTAPI> ZTUAGRI_HK_TESTAPI { get; set; }
        public virtual DbSet<ZTU_PRCALCHV_TESTAPI> ZTU_PRCALCHV_TESTAPI { get; set; }
        public virtual DbSet<ZTUAGRI_BP_TESTAPI> ZTUAGRI_BP_TESTAPI { get; set; }
        public virtual DbSet<ZTUAGRI_PBS2_TESTAPI> ZTUAGRI_PBS2_TESTAPI { get; set; }
        public virtual DbSet<ZTUAGRI_BP> ZTUAGRI_BP { get; set; }
        public virtual DbSet<ZTU_PRCALCHV> ZTU_PRCALCHV { get; set; }
        public virtual DbSet<ZTUAGRI_PBS2> ZTUAGRI_PBS2 { get; set; }
        public virtual DbSet<ZTUAGRI_LB> ZTUAGRI_LB { get; set; }
    }
}
