//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriIACData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTU_PRCALCHV
    {
        public string COMPANY { get; set; }
        public string ESTATE { get; set; }
        public int ZYEAR { get; set; }
        public string BKMNUM { get; set; }
        public System.DateTime BKMDATE { get; set; }
        public string DIVISI { get; set; }
        public string MDRAN { get; set; }
        public string EMPID { get; set; }
        public short LINENUM { get; set; }
        public string BLOCKID { get; set; }
        public string PREMITYP { get; set; }
        public string PRODTYPE { get; set; }
        public Nullable<decimal> BLOCKBASIS { get; set; }
        public Nullable<decimal> BLOCKBASISAVG { get; set; }
        public Nullable<decimal> PREST { get; set; }
        public Nullable<decimal> BASIC { get; set; }
        public Nullable<decimal> BASICPREMI { get; set; }
        public Nullable<decimal> OVERBASIC { get; set; }
        public Nullable<decimal> OVERBASICRATE { get; set; }
        public Nullable<decimal> OVERBASICPREMI { get; set; }
        public Nullable<decimal> ALOCPREMI { get; set; }
        public Nullable<decimal> TOTALPREMI { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
    }
}
