//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriIACData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTUAGRI_HK
    {
        public string BKMNUM { get; set; }
        public int ZYEAR { get; set; }
        public string COMPANY_CODE { get; set; }
        public string ESTATE { get; set; }
        public string DIVISI { get; set; }
        public string MDRAN { get; set; }
        public System.DateTime BKMDATE { get; set; }
        public Nullable<int> WEEK { get; set; }
        public Nullable<int> PERIOD { get; set; }
        public string MANDOR { get; set; }
        public string KRANI { get; set; }
        public string STATUS { get; set; }
        public string REVIEW { get; set; }
        public string SAPNUM { get; set; }
        public string REFDOC { get; set; }
        public string UPLOAD { get; set; }
        public int LINENUM { get; set; }
        public string EMPID { get; set; }
        public string ACTID { get; set; }
        public string LOCID { get; set; }
        public string LOCCC { get; set; }
        public Nullable<decimal> HK { get; set; }
        public string UOM_HK { get; set; }
        public Nullable<decimal> OT { get; set; }
        public string UOM_OT { get; set; }
        public Nullable<decimal> HASIL { get; set; }
        public string UOM { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> PREMI { get; set; }
        public Nullable<decimal> PENALTI { get; set; }
        public string WAERS { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string ABSTYPE { get; set; }
        public string KOSTL { get; set; }
        public string JOBPOS { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> LINENUMREF { get; set; }
        public string TYPEID { get; set; }
        public Nullable<System.DateTime> Exec_Date { get; set; }
        public string Exec_Time { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
