//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriIACData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTUAGRI_LB
    {
        public string COMPANY_CODE { get; set; }
        public string LBKNUM { get; set; }
        public int ZYEAR { get; set; }
        public string ESTATE { get; set; }
        public string DIVISI { get; set; }
        public string MDRAN { get; set; }
        public System.DateTime LBKDATE { get; set; }
        public Nullable<int> WEEK { get; set; }
        public Nullable<int> PERIOD { get; set; }
        public string MANDOR { get; set; }
        public string KRANI { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string REVIEW { get; set; }
        public string SAPNUM { get; set; }
        public string REFDOC { get; set; }
        public string UPLOAD { get; set; }
        public string HISTORY { get; set; }
        public string SPBSNUM { get; set; }
        public int LINENUM { get; set; }
        public string RUNACC { get; set; }
        public string EMPID { get; set; }
        public string ACTID { get; set; }
        public string TYPEID { get; set; }
        public string LOCID { get; set; }
        public string LOCCC { get; set; }
        public Nullable<decimal> JARAK { get; set; }
        public string UOM { get; set; }
        public string TYPEANGK { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string UOMQTY { get; set; }
        public string KERNET { get; set; }
        public Nullable<System.DateTime> CREATEDDATE_I { get; set; }
        public string CREATEDBY_I { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATEI { get; set; }
        public string LASTUPDATEDBY_I { get; set; }
        public string HSTART { get; set; }
        public string HEND { get; set; }
        public string REMARK { get; set; }
        public string REVIEW_I { get; set; }
        public string PCIO { get; set; }
        public Nullable<int> TRIPC { get; set; }
        public string DEST { get; set; }
        public string FTRIP { get; set; }
        public string DOCNUM { get; set; }
        public Nullable<int> DOCLINE { get; set; }
        public string EBELN { get; set; }
        public string CONTRACTNUM { get; set; }
        public string DONUM { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
