//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriIACData.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTUAGRI_PBS2
    {
        public int ZYEAR { get; set; }
        public string SPBSNUM { get; set; }
        public string COMPANY_CODE { get; set; }
        public string ESTATE { get; set; }
        public string DIVISI { get; set; }
        public Nullable<System.DateTime> SPBSDATE { get; set; }
        public string PLASMAID { get; set; }
        public string ASSTID { get; set; }
        public string KRANI { get; set; }
        public string MILL { get; set; }
        public string MILLEX { get; set; }
        public string SOPIR { get; set; }
        public Nullable<decimal> JARAK { get; set; }
        public string NOPOL { get; set; }
        public string WBNUM { get; set; }
        public Nullable<decimal> NET { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATE { get; set; }
        public string LASTUPDATEDBY { get; set; }
        public string UOM { get; set; }
        public string UOMJRK { get; set; }
        public string REVIEW { get; set; }
        public string SAPNUM { get; set; }
        public string REFDOC { get; set; }
        public string STATUS { get; set; }
        public string INEX { get; set; }
        public string RECALNUM { get; set; }
        public Nullable<System.DateTime> LOADDATE { get; set; }
        public string MULTI { get; set; }
        public string ACTPLASMA { get; set; }
        public string UPLOAD { get; set; }
        public string LBKNUM { get; set; }
        public string RUNNING_ACCOUNT { get; set; }
        public int LINENUM { get; set; }
        public string BLOCKID { get; set; }
        public Nullable<System.DateTime> ZDATE { get; set; }
        public Nullable<decimal> JANJANG { get; set; }
        public string JJGUOM { get; set; }
        public Nullable<decimal> TAKJANJANG { get; set; }
        public Nullable<decimal> TAKBROND { get; set; }
        public Nullable<decimal> TAKTOTAL { get; set; }
        public Nullable<decimal> ACTUAL { get; set; }
        public string LBKNUM_ITEM { get; set; }
        public string SHIPTYPE { get; set; }
        public Nullable<System.DateTime> SHIPDATE { get; set; }
        public Nullable<int> SHIPTRIP { get; set; }
        public Nullable<int> WEEK { get; set; }
        public Nullable<int> PERIODE { get; set; }
        public string kernet { get; set; }
        public string WBNUMEST { get; set; }
        public Nullable<decimal> NETEST { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
