//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoAgri.SapToDB.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisition
    {
        public string BANFN { get; set; }
        public string BNFPO { get; set; }
        public string MATNR { get; set; }
        public string TXZ01 { get; set; }
        public string MATKL { get; set; }
        public string MEINS { get; set; }
        public decimal MENGE { get; set; }
        public string WERKS { get; set; }
        public System.DateTime BADAT { get; set; }
        public System.DateTime LFDAT { get; set; }
        public string FRGZU { get; set; }
        public decimal PREIS { get; set; }
        public string WAERS { get; set; }
        public string DISPO { get; set; }
        public string ESTKZ { get; set; }
        public string FRGKZ { get; set; }
        public string EKGRP { get; set; }
        public string HDRTXT { get; set; }
        public string EXTWG { get; set; }
        public string NORMT { get; set; }
        public bool IsUsed { get; set; }
        public string SAKTO { get; set; }
        public string KOSTL { get; set; }
        public string ANLN1 { get; set; }
        public string ANLN2 { get; set; }
        public string AUFNR { get; set; }
        public string PS_PSP_PNR { get; set; }
        public string Pspnr { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
