//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indoagri.IndoagriDB217.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequestDetail
    {
        public int prd_ID { get; set; }
        public Nullable<System.Guid> prd_crID { get; set; }
        public string prd_PO_Number { get; set; }
        public string prd_Status { get; set; }
        public string prd_ProductCode { get; set; }
        public string prd_ProductName { get; set; }
        public string prd_VendorCode { get; set; }
        public int prd_CityID { get; set; }
        public int prd_PurchaseID { get; set; }
        public string prd_WERKS { get; set; }
        public Nullable<bool> prd_CapexOpex { get; set; }
        public string prd_GoodsType { get; set; }
        public string prd_PSPNR_WBS { get; set; }
        public string prd_POSID_WBS { get; set; }
        public string prd_BUKRS { get; set; }
        public string prd_ANLN1_Asset { get; set; }
        public string prd_KOKRS_CostCenter { get; set; }
        public string prd_KOSTL_CostCenter { get; set; }
        public string prd_KTOPL_GLAcc { get; set; }
        public string prd_SAKNR_GLAcc { get; set; }
        public string prd_UOM { get; set; }
        public decimal prd_Qty { get; set; }
        public Nullable<System.DateTime> prd_DeliveryDate { get; set; }
        public string prd_Remark { get; set; }
        public string prd_CashflowCode { get; set; }
        public string prd_Currency { get; set; }
        public Nullable<decimal> prd_Price { get; set; }
        public Nullable<decimal> prd_SalePrice { get; set; }
        public Nullable<decimal> prd_DiscountQty { get; set; }
        public Nullable<int> prd_UserId { get; set; }
        public string deliveryAddrWERKS { get; set; }
        public string deliveryAddrADDRNUMBER { get; set; }
        public string prd_emailDeliveryAddress { get; set; }
        public string invoiceAddrWERKS { get; set; }
        public string invoiceAddrADDRNUMBER { get; set; }
        public string invoiceAddrLGORT { get; set; }
        public Nullable<bool> ThirdPartyTransporter { get; set; }
        public string Transporter { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string prd_BANFN { get; set; }
        public string prd_BNFPO { get; set; }
        public string prd_PRNo { get; set; }
        public string prd_PRItem { get; set; }
        public string prd_OrderNo { get; set; }
        public string RejectCommentAMAAME { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
    }
}
